// frontend/src/views/LoginView.tsx
import React, { useState } from 'react'
import { RadioTower, Lock, User, ArrowRight, ShieldCheck, AlertCircle } from 'lucide-react'
import { useAuth } from '../context/AuthContext'

export const LoginView: React.FC = () => {
  const { login } = useAuth()

  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const appVersion = (window as any).__APP_VERSION__ || '0.6.0'

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!username.trim() || !password) {
      setError('Please provide username and password.')
      return
    }
    setLoading(true)
    setError('')
    try {
      const res = await login(username, password)
      if (res.success) {
        window.location.href = '/'
      } else {
        setError(res.error || 'Invalid username or password')
        setLoading(false)
      }
    } catch (err: any) {
      setError(err.backendError || err.message || 'Connection error. Is the server running?')
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-slate-950 flex flex-col items-center justify-center p-4 relative overflow-hidden font-sans">
      {/* Background Cyber Grid & Glow */}
      <div className="absolute inset-0 bg-grid-pattern opacity-40 pointer-events-none" />
      <div className="absolute w-[600px] h-[600px] rounded-full bg-cyan-500/10 blur-[120px] pointer-events-none top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />

      {/* Watermelon Studio Card */}
      <div className="w-full max-w-md relative z-10">
        <div className="rounded-2xl bg-slate-900/90 border border-slate-800 p-8 sm:p-10 shadow-2xl shadow-black/80 backdrop-blur-xl">
          {/* Top Accent Line */}
          <div className="absolute top-0 left-12 right-12 h-[2px] bg-gradient-to-r from-transparent via-cyan-400 to-transparent" />

          {/* Logo & Header */}
          <div className="text-center mb-8">
            <div className="w-14 h-14 mx-auto rounded-2xl bg-gradient-to-tr from-cyan-600 to-cyan-400 p-[1px] shadow-glow-cyan mb-4">
              <div className="w-full h-full rounded-2xl bg-slate-950 flex items-center justify-center text-cyan-400">
                <RadioTower className="w-7 h-7 animate-pulse" />
              </div>
            </div>
            <h1 className="text-2xl font-bold tracking-wider text-slate-100 uppercase">
              Smart NOC
            </h1>
            <p className="text-xs font-mono text-cyan-400/80 tracking-widest mt-1">
              v{appVersion} &bull; Network Operations Center
            </p>
          </div>

          {/* Error Alert */}
          {error && (
            <div className="mb-6 p-3 rounded-xl bg-rose-500/10 border border-rose-500/30 flex items-center gap-2.5 text-xs text-rose-400 font-mono">
              <AlertCircle className="w-4 h-4 shrink-0" />
              <span>{error}</span>
            </div>
          )}

          {/* Form */}
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-xs font-mono uppercase tracking-widest text-slate-400 mb-1.5">
                Username
              </label>
              <div className="relative">
                <User className="w-4 h-4 text-slate-500 absolute left-3.5 top-1/2 -translate-y-1/2" />
                <input
                  type="text"
                  value={username}
                  onChange={e => setUsername(e.target.value)}
                  placeholder="admin"
                  autoFocus
                  className="w-full bg-slate-950/80 border border-slate-800 rounded-xl pl-10 pr-4 py-2.5 text-sm text-slate-100 placeholder:text-slate-600 focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500/50 transition-all font-mono"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-mono uppercase tracking-widest text-slate-400 mb-1.5">
                Password
              </label>
              <div className="relative">
                <Lock className="w-4 h-4 text-slate-500 absolute left-3.5 top-1/2 -translate-y-1/2" />
                <input
                  type="password"
                  value={password}
                  onChange={e => setPassword(e.target.value)}
                  placeholder="••••••••"
                  className="w-full bg-slate-950/80 border border-slate-800 rounded-xl pl-10 pr-4 py-2.5 text-sm text-slate-100 placeholder:text-slate-600 focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500/50 transition-all font-mono"
                />
              </div>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full mt-6 py-3 rounded-xl font-bold text-sm tracking-wider uppercase bg-gradient-to-r from-cyan-500 to-cyan-400 hover:from-cyan-400 hover:to-cyan-300 text-slate-950 shadow-lg shadow-cyan-500/25 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
            >
              <span>{loading ? 'Authenticating...' : 'Sign In'}</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </form>

          {/* Footer Security Badge */}
          <div className="mt-8 pt-6 border-t border-slate-800/80 flex items-center justify-center gap-2 text-[11px] font-mono text-slate-500">
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
            <span>Encrypted Session &bull; 24/7 Operations</span>
          </div>
        </div>
      </div>
    </div>
  )
}

// frontend/src/views/LoginView.vue
﻿<template>
  <div class="login-wrapper">
    <div class="login-glow"></div>
    <div class="login-card">
      <div class="logo">
        <div class="logo-icon">&#128225;</div>
        <h1>Smart NOC</h1>
        <p>v{{ appVersion }} &mdash; Network Operations Center</p>
      </div>
      <div v-if="error" class="login-error">{{ error }}</div>
      <div class="form-group">
        <label>Username</label>
        <input v-model="username" type="text" placeholder="Enter username" autocomplete="username" autofocus @keydown.enter="doLogin" />
      </div>
      <div class="form-group">
        <label>Password</label>
        <input v-model="password" type="password" placeholder="Enter password" autocomplete="current-password" @keydown.enter="doLogin" />
      </div>
      <button class="login-btn" :disabled="loading" @click="doLogin">
        {{ loading ? 'Authenticating...' : 'Login' }}
      </button>
      <div class="footer">Secure access &mdash; Smart NOC v{{ appVersion }}</div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()
const username = ref('')
const password = ref('')
const error = ref('')
const loading = ref(false)
const appVersion = window.__APP_VERSION__ || '0.5.6.4'

async function doLogin() {
  if (!username.value.trim() || !password.value) {
    error.value = 'Please enter username and password'
    return
  }
  loading.value = true
  error.value = ''
  try {
    const r = await fetch('/api/auth/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify({ username: username.value.trim(), password: password.value })
    })
    const d = await r.json()
    if (d.success) {
      router.push('/')
    } else {
      error.value = d.error || 'Login failed'
      loading.value = false
    }
  } catch (e) {
    error.value = 'Connection error. Is the server running?'
    loading.value = false
  }
}
</script>

<style scoped>
.login-wrapper {
  position: relative;
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  background: #050c13;
  font-family: 'Rajdhani', sans-serif;
}
.login-wrapper::before {
  content: '';
  position: fixed;
  inset: 0;
  background: repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(0,229,255,0.015) 2px, rgba(0,229,255,0.015) 4px);
  pointer-events: none;
  z-index: 0;
}
.login-wrapper::after {
  content: '';
  position: fixed;
  inset: 0;
  background-image: linear-gradient(rgba(0,229,255,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(0,229,255,0.03) 1px, transparent 1px);
  background-size: 40px 40px;
  pointer-events: none;
  z-index: 0;
}
.login-glow {
  position: fixed;
  width: 600px; height: 600px;
  border-radius: 50%;
  background: radial-gradient(circle, rgba(0,229,255,0.06) 0%, transparent 70%);
  top: 50%; left: 50%;
  transform: translate(-50%, -50%);
  pointer-events: none;
  z-index: 0;
}
.login-card {
  position: relative;
  z-index: 10;
  background: rgba(10, 21, 32, 0.95);
  border: 1px solid #0f2a3f;
  border-radius: 12px;
  padding: 44px 40px;
  width: 100%;
  max-width: 400px;
  box-shadow: 0 0 60px rgba(0,229,255,0.08), 0 0 120px rgba(0,0,0,0.8);
}
.login-card::before {
  content: '';
  position: absolute;
  top: 0; left: 20%; right: 20%;
  height: 1px;
  background: linear-gradient(90deg, transparent, #00e5ff, transparent);
}
.logo { text-align: center; margin-bottom: 32px; }
.logo-icon {
  width: 52px; height: 52px;
  border: 2px solid #00e5ff; border-radius: 10px;
  display: flex; align-items: center; justify-content: center;
  font-size: 22px;
  margin: 0 auto 14px;
  box-shadow: 0 0 20px rgba(0,229,255,0.3);
  animation: pulse 2.5s ease-in-out infinite;
}
@keyframes pulse {
  0%, 100% { box-shadow: 0 0 20px rgba(0,229,255,0.3); }
  50% { box-shadow: 0 0 40px rgba(0,229,255,0.7); }
}
.logo h1 {
  font-size: 24px; font-weight: 700;
  letter-spacing: 4px; color: #00e5ff;
  text-shadow: 0 0 20px rgba(0,229,255,0.5);
}
.logo p {
  font-size: 11px; color: #3a6070;
  letter-spacing: 2px;
  font-family: 'Share Tech Mono', monospace;
  margin-top: 4px;
}
.form-group { margin-bottom: 20px; }
.form-group label {
  display: block; font-size: 10px;
  letter-spacing: 2px; color: #5c7d92;
  margin-bottom: 8px;
  font-family: 'Share Tech Mono', monospace;
}
.form-group input {
  width: 100%;
  background: rgba(0, 229, 255, 0.03);
  border: 1px solid #0f2a3f;
  border-radius: 6px;
  padding: 12px 14px;
  color: #cde8f5;
  font-family: 'Rajdhani', sans-serif;
  font-size: 15px;
  outline: none;
  transition: all 0.2s ease;
}
.form-group input:focus {
  border-color: #00e5ff;
  box-shadow: 0 0 15px rgba(0,229,255,0.15);
  background: rgba(0, 229, 255, 0.05);
}
.form-group input::placeholder { color: #2a4a5f; }
.login-error {
  background: rgba(255,45,85,0.08);
  border: 1px solid rgba(255,45,85,0.3);
  color: #ff2d55;
  padding: 10px 14px;
  border-radius: 6px;
  font-size: 13px;
  margin-bottom: 18px;
  text-align: center;
}
.login-btn {
  width: 100%;
  background: linear-gradient(135deg, rgba(0,229,255,0.12), rgba(0,229,255,0.04));
  border: 1px solid #00e5ff;
  color: #00e5ff;
  padding: 13px;
  border-radius: 6px;
  font-family: 'Rajdhani', sans-serif;
  font-size: 15px;
  font-weight: 700;
  letter-spacing: 3px;
  cursor: pointer;
  transition: all 0.2s ease;
  text-transform: uppercase;
}
.login-btn:hover:not(:disabled) {
  background: rgba(0,229,255,0.2);
  box-shadow: 0 0 25px rgba(0,229,255,0.4);
}
.login-btn:disabled { opacity: 0.5; cursor: not-allowed; }
.footer {
  text-align: center;
  margin-top: 24px;
  font-size: 10px;
  color: #2a4a5f;
  letter-spacing: 1px;
  font-family: 'Share Tech Mono', monospace;
}
</style>
